### PR TITLE
Rpc for geode

### PR DESCRIPTION
**Pull request by Ljiacheng**
1. Add two jsonrpc for geode. Both functions have no params.
   1. `attestor_list() -> Vec<(Vec<u8>, Vec<u8>)>`
    Return the registered attestors' “url” and “pubkey” by vector

    2. `registered_geodes() -> Vec<Geodes>`
    Return the registered(not attested) geodes' record by vector

2. Set time limit to **u64::max_value()** in case that geode which registered but can't get enough attestors at limited blocks will be deleted.
    This is because we need a long time runing geode which is registered but not attested currently.

### CODE REVIEW

**Review by Kayryu — APPROVED** [review]
Approve

**Comment by melynx** [comment]
Looks good. Not part of the commit but can you do a quick fix on the check failures?

**Review by melynx — APPROVED** [review]

**Comment by Ljiacheng** [comment]
Well, I find that check failures(by clippy) can't be found together at one time. When I fix them, there will be more at another commit.
These warnings and errors are caused by redundant syntax and some unimplemented logics. And the clippy check rule is strict.
Maybe we should fix those warings together and create a new PR next time?

**Comment by melynx** [comment]
I'm ok with that. Merging the PR into master.

**Comment by melynx** [comment]
Merged the PR into master. Let's address the CI errors in another PR.

**Pull request merged**
